/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package MyLauncher.app.view;

import MyLauncher.app.model.MemberDTO;
import MyLauncher.app.model.RoomDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author jseun
 */
public class FirstView extends javax.swing.JFrame implements ActionListener{
    String id;
    /**
     * Creates new form FirstView
     */
    public FirstView() {
        initComponents();
        init();
        addEvent();
        
    }

    public FirstView(String id) {
        this();
        this.id=id;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel3 = new javax.swing.JPanel();
        btMotel = new javax.swing.JButton();
        btHotel = new javax.swing.JButton();
        btGeustHouse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btHome = new javax.swing.JButton();
        btSurrounding = new javax.swing.JButton();
        btMyHome = new javax.swing.JButton();
        btSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logo.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        logo.setText("Gaza");

        tfSearch.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        tfSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfSearchMouseClicked(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btMotel.setText("모텔");
        btMotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMotelActionPerformed(evt);
            }
        });

        btHotel.setText("호텔");
        btHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHotelActionPerformed(evt);
            }
        });

        btGeustHouse.setText("게스트하우스");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyLauncher/app/image/집..jpg"))); // NOI18N

        btHome.setText("홈");
        btHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHomeActionPerformed(evt);
            }
        });

        btSurrounding.setText("내주변");
        btSurrounding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSurroundingActionPerformed(evt);
            }
        });

        btMyHome.setText("MyHome");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSurrounding)
                        .addGap(48, 48, 48)
                        .addComponent(btMyHome))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btMotel)
                        .addGap(45, 45, 45)
                        .addComponent(btHotel)
                        .addGap(29, 29, 29)
                        .addComponent(btGeustHouse)))
                .addGap(42, 42, 42))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btHotel)
                    .addComponent(btGeustHouse)
                    .addComponent(btMotel))
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btHome)
                    .addComponent(btSurrounding)
                    .addComponent(btMyHome))
                .addGap(27, 27, 27))
        );

        btSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyLauncher/app/image/search.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logo)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSearch))
                .addGap(4, 4, 4)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btMotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMotelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btMotelActionPerformed
    
    private void btSurroundingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSurroundingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSurroundingActionPerformed
    
    private void btHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHotelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btHotelActionPerformed
    
    private void btHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btHomeActionPerformed

    private void tfSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSearchMouseClicked
        Search f = new Search(id);
            f.setVisible(true);
    }//GEN-LAST:event_tfSearchMouseClicked
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstView().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGeustHouse;
    private javax.swing.JButton btHome;
    private javax.swing.JButton btHotel;
    private javax.swing.JButton btMotel;
    private javax.swing.JButton btMyHome;
    private javax.swing.JButton btSearch;
    private javax.swing.JButton btSurrounding;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
    
    private void init() {
    }
    
    private void addEvent() {
        btMyHome.addActionListener(this);
        btMotel.addActionListener(this);
        btHotel.addActionListener(this);
        btGeustHouse.addActionListener(this);
        btSurrounding.addActionListener(this);
        tfSearch.addActionListener(this);
        btSearch.addActionListener(this);
        
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==btMyHome){
            this.dispose();
            LoginGUI f = new LoginGUI();
            f.setVisible(true);
        }else if(e.getSource()==btMotel){
            String motel ="모텔";
            if(id!=null){
                Search f = new Search(motel, id);
                f.setVisible(true);
            }else{
                Search f = new Search(motel);
                f.setVisible(true);
            }
                
        }else if(e.getSource()==btHotel){
            String hotel ="호텔";
            if(id!=null){
                Search f = new Search(hotel, id);
                f.setVisible(true);
            }else{
                Search f = new Search(hotel);
                f.setVisible(true);
            }
        }else if(e.getSource()==btGeustHouse){
            String geustHouse ="게스트하우스";
            if(id!=null){
                Search f = new Search(geustHouse, id);
                f.setVisible(true);
            }else{
                Search f = new Search(geustHouse);
                f.setVisible(true);
            }
        }else if(e.getSource()==btSurrounding){
            String dong = JOptionPane.showInputDialog("현재 동을 입력하세요(예.삼성동)");
            Search f = new Search(dong);
            f.setVisible(true);
        }else if(e.getSource()==btSearch){
            Search f = new Search(id);
            f.setVisible(true);
        }
    }

}
