/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.swingapp.view;

import com.swingapp.product.model.ProductDAO;
import com.swingapp.product.model.ProductDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TEA
 */
public class ProductMain extends javax.swing.JFrame
        implements  ItemListener{
    private String[] colNames={"번호","상품명","가격"};
    private DefaultTableModel model;
    private ProductDAO dao;
    private String userid;
    
    /**
     * Creates new form ProductMain
     */
    public ProductMain() {
        initComponents();
        init();
        addEvent();
    }
    
    public ProductMain(String userid){
        this();
        
        this.userid=userid;
        tfUserid.setText(userid);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        btAdd = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btDel = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        btMemEdit = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();
        tab1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tfNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfPdName = new javax.swing.JTextField();
        tfPrice = new javax.swing.JTextField();
        tfRegdate = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDesc = new javax.swing.JTextArea();
        tab2 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rdPdName = new javax.swing.JRadioButton();
        rdPrice = new javax.swing.JRadioButton();
        cbPdName = new javax.swing.JComboBox<>();
        tfPrice1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfPrice2 = new javax.swing.JTextField();
        btSearch = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        tfUserid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("상품 관리");

        jToolBar1.setRollover(true);

        btAdd.setText("등록");
        btAdd.setFocusable(false);
        btAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });
        jToolBar1.add(btAdd);

        btEdit.setText("수정");
        btEdit.setFocusable(false);
        btEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btEdit);

        btDel.setText("삭제");
        btDel.setFocusable(false);
        btDel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btDel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btDel);

        btExit.setText("종료");
        btExit.setFocusable(false);
        btExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btExit);

        btMemEdit.setText("회원수정");
        btMemEdit.setFocusable(false);
        btMemEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMemEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btMemEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMemEditActionPerformed(evt);
            }
        });
        jToolBar1.add(btMemEdit);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "번호", "상품명", "가격"
            }
        ));
        jScrollPane1.setViewportView(table);

        jLabel1.setText("상품번호");

        tfNo.setEditable(false);

        jLabel2.setText("상품명");

        jLabel3.setText("가격");

        jLabel4.setText("등록일");

        tfRegdate.setEditable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("상품설명"));

        taDesc.setColumns(20);
        taDesc.setLineWrap(true);
        taDesc.setRows(5);
        jScrollPane2.setViewportView(taDesc);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab1Layout.createSequentialGroup()
                        .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfRegdate, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addComponent(tfPrice)
                            .addComponent(tfPdName)
                            .addComponent(tfNo)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 53, Short.MAX_VALUE))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfPdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfRegdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tab1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabbedPane.addTab("상품등록", tab1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("조회조건"));

        group.add(rdPdName);
        rdPdName.setSelected(true);
        rdPdName.setText("상품명으로 검색");

        group.add(rdPrice);
        rdPrice.setText("가격으로 검색");

        cbPdName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("~");

        btSearch.setText("검색");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdPdName)
                    .addComponent(rdPrice))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tfPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(tfPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btSearch))
                    .addComponent(cbPdName, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(347, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdPdName)
                    .addComponent(cbPdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdPrice)
                    .addComponent(tfPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSearch))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "번호", "상품명", "가격", "설명", "등록일"
            }
        ));
        jScrollPane3.setViewportView(table2);

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab2Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        tabbedPane.addTab("상품검색", tab2);

        jLabel6.setText("아이디");

        tfUserid.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabbedPane)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(tfUserid, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfUserid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        try {
            addPd();
            clear_tf();
            showAll();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btAddActionPerformed

    private void btMemEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMemEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btMemEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btDel;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btMemEdit;
    private javax.swing.JButton btSearch;
    private javax.swing.JComboBox<String> cbPdName;
    private javax.swing.ButtonGroup group;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JRadioButton rdPdName;
    private javax.swing.JRadioButton rdPrice;
    private javax.swing.JTextArea taDesc;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable table;
    private javax.swing.JTable table2;
    private javax.swing.JTextField tfNo;
    private javax.swing.JTextField tfPdName;
    private javax.swing.JTextField tfPrice;
    private javax.swing.JTextField tfPrice1;
    private javax.swing.JTextField tfPrice2;
    private javax.swing.JTextField tfRegdate;
    private javax.swing.JTextField tfUserid;
    // End of variables declaration//GEN-END:variables

    private void init() {
        dao = new ProductDAO();
        model = new DefaultTableModel();
        
        try {
            showAll();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
    }

    private void showAll() throws SQLException {
        //1.        
        //2. db
        ArrayList<ProductDTO> list =dao.selectAll();
        
        //3.
        if(list==null || list.isEmpty()){
            JOptionPane.showMessageDialog(this, "데이터가 없습니다.");
            return;
        }
        
        DecimalFormat df = new DecimalFormat("#,###");
        //table에 db에서 읽어온 데이터를 출력해야 한다
        //1) String 2차원 배열이 필요함
        String[][] data = new String[list.size()][3];
        for(int i=0;i<list.size();i++){
            ProductDTO dto = list.get(i);
            
            //2) 2차원 배열에  dto 의 값을 넣는다
            data[i][0] = dto.getNo()+"";
            data[i][1] = dto.getProductName();
            data[i][2] = df.format(dto.getPrice());            
        }//for
        
        //3) model 에 2차원 배열의 데이터를 넣는다
        model.setDataVector(data, colNames);
        
        //4) table 에  model 을 연결해서  model의 데이터가 table 에
        //보여지게 한다
        table.setModel(model);
        
        //각 컬럼 사이즈 조절하기
        table.getColumnModel().getColumn(0).setPreferredWidth(40);
        table.getColumnModel().getColumn(1).setPreferredWidth(120);
        //table.getColumnModel().getColumn(2).setPreferredWidth(60);

        //가격 오른쪽 정렬하기
        DefaultTableCellRenderer dtcr = new DefaultTableCellRenderer();
        dtcr.setHorizontalAlignment(SwingConstants.RIGHT);
        table.getColumnModel().getColumn(2).setCellRenderer(dtcr);	
    }

    private void addPd() throws SQLException {
        //1
        String pdName=tfPdName.getText();
        String price=tfPrice.getText();
        String desc=taDesc.getText();
        
        if(pdName==null || pdName.isEmpty()){
            JOptionPane.showMessageDialog(this, "상품명을 입력해야 합니다!");
            tfPdName.requestFocus();
            return;
        }
        
        //2. db
        ProductDTO dto = new ProductDTO();
        dto.setDescription(desc);
        dto.setPrice(Integer.parseInt(price));
        dto.setProductName(pdName);
        
        int cnt = dao.insertPd(dto);
        
        //3
        String result="";
        if(cnt>0){
            result="상품 등록되었습니다.";
        }else{
            result="상품 등록 실패!";            
        }
        
        JOptionPane.showMessageDialog(this, result);
    }

    private void clear_tf() {
        tfNo.setText("");
        tfPdName.setText("");
        tfPrice.setText("");
        tfRegdate.setText("");
        taDesc.setText("");
        
    }

    private void addEvent() {
        table.addMouseListener(new EventHandler());
        btEdit.addActionListener(new EventHandler());
        btDel.addActionListener(new EventHandler());
        btMemEdit.addActionListener(new EventHandler());
        
        cbPdName.addItemListener(this);
        
        tabbedPane.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                JTabbedPane tpane=(JTabbedPane) e.getSource();
                int index=tpane.getSelectedIndex();
                System.out.println("선택한 index="+ index);
                
                if(index==0){
                    clear_tf();
                    try {
                        showAll();
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }
                }else if(index==1){
                    clear_tf2();
                }
            }

            
            
        });
    }
    
    private void clear_tf2() {
        rdPdName.setSelected(true);
        tfPrice1.setText("");
        tfPrice2.setText("");
        
        //상품명 조회해서 콤보박스에 출력
        showPdName();
    }

    private void showPdName() {
        try {
            //1
            //2
            Vector<String> vec=dao.selectPdName();
            
            //3
            DefaultComboBoxModel comboModel 
                    = new DefaultComboBoxModel(vec);
            cbPdName.setModel(comboModel);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
    }

    @Override
    public void itemStateChanged(ItemEvent e) {
        //콤보박스가 선택되면 '상품명으로 검색' 라디오버튼이 자동으로
        //선택되도록 설정
        if(e.getSource()==cbPdName){
            if(e.getStateChange() == ItemEvent.SELECTED){
                rdPdName.setSelected(true);                
            }
        }//if
    }
    
    class EventHandler extends MouseAdapter implements ActionListener{

        @Override
        public void mouseClicked(MouseEvent e) {
            int row = table.getSelectedRow();
            String sNo=(String) table.getValueAt(row, 0);
            
            try {
                //no에 해당하는 레코드 조회하기
                //db작업
                ProductDTO dto=dao.selectByNo(Integer.parseInt(sNo));
                
                tfNo.setText(dto.getNo()+"");
                tfPdName.setText(dto.getProductName());
                tfPrice.setText(dto.getPrice()+"");
                tfRegdate.setText(dto.getRegDate()+"");
                taDesc.setText(dto.getDescription());
                
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            try {
                if(e.getSource()==btEdit){
                    //수정
                    editProduct();
                    clear_tf();
                    showAll();
                }else if(e.getSource()==btDel){
                    //삭제
                    delProduct();
                    clear_tf();
                    showAll();
                }else if (e.getSource()==btMemEdit){
                    //회원수정
                    MemberFrame f = new MemberFrame(userid);
                    f.setVisible(true);
                    
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            
        }

        private void editProduct() throws SQLException {
            //1
            String no=tfNo.getText();
            String pdName=tfPdName.getText();
            String price=tfPrice.getText();
            String desc=taDesc.getText();
            
            if(no==null || no.isEmpty()){
                JOptionPane.showMessageDialog(ProductMain.this, 
                        "번호가 선택되도록 하세요!");
                return;
            }
            if(pdName==null || pdName.isEmpty()){
                JOptionPane.showMessageDialog(ProductMain.this,
                        "상품명을 입력해야 합니다!");
                tfPdName.requestFocus();
                return;
            }
            //2
            ProductDTO dto = new ProductDTO();
            dto.setDescription(desc);
            dto.setNo(Integer.parseInt(no));
            dto.setPrice(Integer.parseInt(price));
            dto.setProductName(pdName);
            
            int cnt=dao.updateProduct(dto);
            
            //3
            String result="";
            if(cnt>0){
                result="상품 수정되었습니다.";
            }else{
                result="상품 수정 실패!";                
            }
            
            JOptionPane.showMessageDialog(ProductMain.this, result);
        }

        private void delProduct() {

        }
        
    }
    
}
